// user Action types

export const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
};

export const cartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM_FROM_CART: " REMOVE_ITEM_FROM_CART",
};
